### ISSUE TITLE
review

### ISSUE THREAD

**Issue by ale-strada** [RichardIrala/mascotas-perdidas-webapp-m8-react#1]
Hola @RichardIrala, como va?  Probe la app y todo funciona bien, Felicitaciones!!. Como sugerencia, estaria bueno que el boton para cerrar sesion este mas a mano, pero es una opinion nada mas.

**Comment by RichardIrala** [comment]
Gracias ale-strada joya. Sisi xD me lo han dicho. Lo dejo así porque me gusta jajaja. Cuando se me ocurra una manera en la que se vea bonito en el Header capaaaz lo pongo ahí jaja. Pero por las dudas si es algo que tengo en cuenta. Solo que no lo pongo
